[project]
name = "learning-mcp"
version = "0.1.0"
description = "My first MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.7.1",
    "openai==0.28",
    "requests>=2.32.3",
]

[tool.uv.workspace]
members = [
    "portfolio-mcp-server",
]
